### ISSUE TITLE
Ishihara - Load Image

### ISSUE THREAD

**Issue by SQLGuruZA** [franciscouzo/franciscouzo.github.io#1]
Hi.

Apologies for posting this here as an issue, but I could not find any other contact details for you.
I would like if you could explain how to load an image and then convert that image into an Ishihara generated image. I have tried using numerous settings, but no matter what picture I upload, the ishihara image just appears as random dots.

I basically have a high-res image (PNG with transparent background) of nothing but text. I would like the text embedded in the image - similar to this: http://www.color-blindness.com/wp-content/images/Ishihara-Plate-05-38.jpg

Please feel free to mail me directly. I feel I am doing something wrong or am mis-interpreting the use of you tool (which is awesome by the way).

Thanks!

**Comment by franciscouzo** [comment]
Could you share one or two of the images you've tried with?

**Comment by SQLGuruZA** [comment]
http://tinypic.com/r/mm4m82/9
http://tinypic.com/r/ouvdjo/9

Please don't judge... :)
Ideally, I would like to use a font with thicker lettering... my end goal is to have an image like this one:
http://www.tshirthell.com/shirts/products/a559/a559.gif?v11301bss2

**Comment by franciscouzo** [comment]
The images you linked work fine, I think you might be just colorblind.
Try setting the style to viewable by all, if you can see different dot colors it means you're colorblind.

**Comment by SQLGuruZA** [comment]
here is the viewable by all: http://tinypic.com/r/10hq3vk/9 - yes, legible
here is the one set to colourblind: http://tinypic.com/r/2dbsehi/9 - yes, you can make our the words, but only slightly. 

I am not colourblind, I can see the wording, but a person who does not know the wording struggles to make it out... are there any settings I can change to make it more legible on colour blindness setting?? My brother is colour blind, and cannot see anything in the second link above (which is the point as this is a design going on a tee shirt for him)

BTW - I have changed the image I loaded to this one: http://tinypic.com/r/2egb12f/9

**Comment by franciscouzo** [comment]
The min/max radius is exactly what you want, set it to a low value.

**Comment by SQLGuruZA** [comment]
ok, it took some playing around with the settings, but I finally managed to get this result:
http://tinypic.com/r/w20jcx/9

I will play around with the brightness of the colours a bit in Photoshop.
BTW - download PNG and SVG do not seem to be working.

Thanks for your prompt assistance!
